# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
  schedule:
  - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: initialize
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    
    - name: check repo size
      run: |
        du -h
    
    - name: remove binary files from history (reduce the repo size)
      run: |
        git filter-branch --force --index-filter "git rm --cached --ignore-unmatch bt_blocklist.gz" --prune-empty --tag-name-filter cat -- --all
        rm -rf .git/refs/original/
        git reflog expire --expire=now --all
        git gc --prune=now
        git gc --aggressive --prune=now
      
    - name: install dependencies
      run: |
        sudo apt-get update 
        sudo apt-get install -y wget curl grep gzip findutils git
    
    - name: download from iblocklist
      run: |
        curl -A "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0" -s https://www.iblocklist.com/lists.php \
        | sed -n "s/.*value='\(http:.*\)'.*/\1/p" \
        | sed "s/\&amp;/\&/g" \
        | sed "s/http/\"http/g" \
        | sed "s/gz/gz\"/g" \
        | xargs curl -s -L \
        | gunzip \
        | egrep -v '^#' \
        | sed "/^$/d" > bt_blocklist
        
    # PhantomPeer FR 
    - name: download from iblocklist fr 
      run: |
        curl -A "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0" -s -L "http://list.iblocklist.com/?list=fr&fileformat=p2p&archiveformat=gz&username=${{ secrets.IBLOCKLIST_USERNAME }}&pin=${{ secrets.IBLOCKLIST_PIN }}" | gunzip >> bt_blocklist
      
    # Their ssl cert expired at march 1st 2022 (they renewed    
    - name: download from mirror.codebucket.de 
      run: |
        curl -A "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0" -s https://mirror.codebucket.de/transmission/blocklist.p2p >> bt_blocklist

    - name: remove duplicates
      run: |
        sort --unique bt_blocklist > bt_blocklist_deduplicated
        mv bt_blocklist_deduplicated bt_blocklist
      
    - name: combine all files
      run: |
        gzip -c bt_blocklist > bt_blocklist.gz
        
    - name: check the file size 
      run: |
        check=`du -s bt_blocklist.gz | awk '{print $1}'`

        if [ "$check" -lt 1000 ]
        then
        exit 2
        fi
    
    - name: Push
      run: |
        git add bt_blocklist.gz
        git commit -m "auto update"
        git push origin --force --all
        du -sh .git
        
    - name: check repo size
      run: |
        du -h
        
    - name: Delete the old release
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        delete_release: true
        tag_name: master
        repo: SalemHarrache/bt_blocklist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push the new release
      uses: softprops/action-gh-release@v1
      with:
        name: bt_blocklist
        tag_name: v.1
        files: bt_blocklist.gz
        
    - name: check repo size
      run: |
        du -h
